"""Discover completed EKAP tenders and rank winning companies.

This module uses the public EKAP v2 tender-search endpoints used by the browser
app. Requests include the same public anti-replay headers generated by the
frontend; no login, captcha, paywall, or access-control bypass is used.
"""

from __future__ import annotations

import argparse
import base64
import json
import logging
import os
import re
import time
import uuid
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable

import requests
from bs4 import BeautifulSoup
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
EKAP_BASE_URL = "https://ekapv2.kik.gov.tr"
API_BASE_URL = f"{EKAP_BASE_URL}/b_ihalearama"
SEARCH_PAGE_URL = f"{EKAP_BASE_URL}/ekap/search"
DISCOVERY_OUTPUT = DATA_DIR / "ekap_company_discovery.json"
RANKING_UNIQUE_TENDERS_OUTPUT = DATA_DIR / "ekap_company_ranking_unique_tenders.json"

COMPLETED_STATUS_ID = 15
COMPLETED_FILTER_TYPE = "ResultAnnouncementPublished"
COMPLETED_STATUS_TEXT = "Sonuç İlanı Yayımlanmış"

REQUEST_KEY = b"Qm2LtXR0aByP69vZNKef4wMJ"

BASE_HEADERS = {
    "User-Agent": "TenderIntelligenceMVP/0.4 ekap-public-api-demo",
    "Accept": "application/json",
    "Content-Type": "application/json",
    "Accept-Language": "tr",
    "Origin": EKAP_BASE_URL,
    "Referer": SEARCH_PAGE_URL,
    "api-version": "v1",
}


def _aes_cbc_base64(value: str, iv: bytes) -> str:
    padder = padding.PKCS7(128).padder()
    data = padder.update(value.encode("utf-8")) + padder.finalize()
    cipher = Cipher(algorithms.AES(REQUEST_KEY), modes.CBC(iv), backend=default_backend())
    encryptor = cipher.encryptor()
    encrypted = encryptor.update(data) + encryptor.finalize()
    return base64.b64encode(encrypted).decode("ascii")


def ekap_headers() -> dict[str, str]:
    iv = os.urandom(16)
    request_guid = str(uuid.uuid4())
    request_ts = str(int(time.time() * 1000))
    return {
        **BASE_HEADERS,
        "X-Custom-Request-Ts": _aes_cbc_base64(request_ts, iv),
        "X-Custom-Request-Siv": base64.b64encode(iv).decode("ascii"),
        "X-Custom-Request-R8id": _aes_cbc_base64(request_guid, iv),
        "X-Custom-Request-Guid": request_guid,
    }


def post_ekap(session: requests.Session, path: str, payload: dict, timeout: int = 30) -> dict:
    response = session.post(f"{API_BASE_URL}{path}", headers=ekap_headers(), json=payload, timeout=timeout)
    response.raise_for_status()
    return response.json()


def normalize_company_name(name: str | None) -> str | None:
    if not name:
        return None
    cleaned = " ".join(name.replace("\xa0", " ").split()).strip()
    return cleaned.upper() or None


def clean_text(value: str | None) -> str | None:
    if value is None:
        return None
    cleaned = " ".join(str(value).replace("\xa0", " ").split()).strip()
    return cleaned or None


def parse_try_amount(value: str | int | float | None) -> float | None:
    if value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).replace("\xa0", " ").strip()
    if not text or text in {"-", "Yok"}:
        return None
    if "bulunmamaktadır" in text.casefold():
        return None
    text = re.sub(r"\bTRY\b|\bTL\b|₺", "", text, flags=re.IGNORECASE).strip()
    match = re.search(r"[-+]?\d[\d.,]*", text)
    if not match:
        return None
    number = match.group(0)
    if "," in number and "." in number:
        if number.rfind(",") > number.rfind("."):
            number = number.replace(".", "").replace(",", ".")
        else:
            number = number.replace(",", "")
    elif "," in number:
        number = number.replace(".", "").replace(",", ".")
    try:
        return float(number)
    except ValueError:
        return None


def parse_date(value: str | None) -> str | None:
    if not value:
        return None
    text = value.strip()
    for fmt in ("%d.%m.%Y %H:%M", "%d.%m.%Y", "%Y-%m-%dT%H:%M:%S%z", "%Y-%m-%dT%H:%M:%S"):
        try:
            return datetime.strptime(text, fmt).date().isoformat()
        except ValueError:
            continue
    return text


def source_url_for_ikn(ikn: str | None) -> str:
    if not ikn or "/" not in ikn:
        return SEARCH_PAGE_URL
    return f"{SEARCH_PAGE_URL}/{ikn.replace('/', '_')}"


def _html_text_pairs(html: str | None) -> dict[str, str]:
    if not html:
        return {}
    soup = BeautifulSoup(html, "lxml")
    pairs: dict[str, str] = {}
    for row in soup.select("tr"):
        cells = [cell.get_text(" ", strip=True) for cell in row.select("td")]
        if len(cells) >= 3 and cells[1] == ":":
            key = re.sub(r"^[a-zçğıöşü]\)\s*", "", cells[0], flags=re.IGNORECASE).strip()
            if key:
                pairs[key] = cells[2].strip()
    return pairs


def search_completed_tenders(
    session: requests.Session,
    skip: int = 0,
    take: int = 50,
    search_text: str = "",
) -> dict:
    payload = {
        "paginationSkip": skip,
        "paginationTake": take,
        "orderBy": "ihaleTarihi",
        "siralamaTipi": "desc",
        "filterType": COMPLETED_FILTER_TYPE,
        "searchType": "GirdigimGibi",
        "searchText": search_text,
        "ihaleDurumIdList": [COMPLETED_STATUS_ID],
        "ihaleAdindaAra": True,
        "ihaleIlanindaAra": True,
        "idariSartnamedeAra": True,
        "benzerIsMaddesindeAra": True,
        "isinYapilacagiYerMaddesindeAra": True,
        "nitelikTurMiktarMaddesindeAra": True,
        "ihaleBilgilerindeAra": True,
        "sozlesmeTasarisindaAra": True,
        "teklifCetvelindeAra": True,
        "teknikSartnamedeAra": True,
        "ikNdeAra": True,
    }
    return post_ekap(session, "/api/Ihale/GetListByParameters", payload)


def fetch_tender_detail(session: requests.Session, tender_row: dict) -> dict:
    return post_ekap(session, "/api/IhaleDetay/GetByIhaleIdIhaleDetay", {"ihaleId": tender_row["id"]})


def extract_contract_records(tender_row: dict, detail_payload: dict) -> list[dict]:
    detail = detail_payload.get("item") or {}
    tender_info = detail.get("ihaleBilgi") or {}
    ilan_list = detail.get("ilanList") or []
    result_html = next((item.get("veriHtml") for item in ilan_list if item.get("veriHtml")), None)
    html_pairs = _html_text_pairs(result_html)
    contracts = detail.get("sozlesmeBilgiList") or []
    records: list[dict] = []

    for contract in contracts:
        winner = normalize_company_name(contract.get("yukleniciAdi") or html_pairs.get("Yüklenici"))
        item_list = ((contract.get("kisimItemDto") or {}).get("kisimList") or [])
        item_details_available = bool(item_list)
        base_record = {
            "tender_id": detail.get("ikn") or tender_info.get("ikn") or tender_row.get("ikn"),
            "tender_name": clean_text(detail.get("ihaleAdi") or tender_info.get("ihaleAdi") or tender_row.get("ihaleAdi")),
            "buyer_institution": clean_text(detail.get("idareAdi") or tender_info.get("idareAdi") or tender_row.get("idareAdi")),
            "procurement_type": clean_text(tender_info.get("ihaleTipiAciklama") or tender_row.get("ihaleTipAciklama")),
            "procedure_type": clean_text(tender_info.get("istisnaUsulAciklama")
            or tender_info.get("ihaleUsulAciklama")
            or tender_row.get("istisnaUsulAciklama")
            or tender_row.get("ihaleUsulAciklama")),
            "location": clean_text(tender_info.get("isinYapilacagiYer") or tender_info.get("ihaleYeri") or tender_row.get("ihaleIlAdi")),
            "tender_date": parse_date(tender_info.get("ihaleTarihSaat") or tender_row.get("ihaleTarihSaat")),
            "result_status": clean_text(tender_info.get("ihaleDurumAciklama") or tender_row.get("ihaleDurumAciklama")),
            "winning_company": winner,
            "contract_value_try": parse_try_amount(contract.get("sozlesmeBedeli")),
            "estimated_cost_try": parse_try_amount(contract.get("yaklasikMaliyet")),
            "contract_date": parse_date(contract.get("sozlesmeTarih") or html_pairs.get("Tarihi")),
            "highest_bid_try": parse_try_amount(contract.get("enYuksekTeklif")),
            "lowest_bid_try": parse_try_amount(contract.get("enDusukTeklif")),
            "termination_status": contract.get("fesihString"),
            "transfer_status": contract.get("tasfiyeTransferString"),
            "item_details_available": item_details_available,
            "source_url": source_url_for_ikn(detail.get("ikn") or tender_row.get("ikn")),
            "source_type": "EKAP completed tender detail",
            "extraction_confidence": "high" if winner and contract.get("sozlesmeBedeli") else "medium",
            "notes": "Official EKAP v2 detail response.",
        }
        if item_list:
            for item in item_list:
                item_value = parse_try_amount(item.get("sozlesmeBedeli") or item.get("enDusukTeklif"))
                records.append(
                    {
                        **base_record,
                        "item_name": clean_text(item.get("kisimAdi")),
                        "quantity": None,
                        "unit": None,
                        "item_contract_value_try": item_value,
                        "item_unit_price_try": None,
                    }
                )
        else:
            records.append(
                {
                    **base_record,
                    "item_name": None,
                    "quantity": None,
                    "unit": None,
                    "item_contract_value_try": None,
                    "item_unit_price_try": None,
                }
            )
    return records


def dedupe_records(records: Iterable[dict]) -> list[dict]:
    seen: set[tuple] = set()
    output: list[dict] = []
    for record in records:
        key = (
            record.get("tender_id"),
            record.get("winning_company"),
            record.get("contract_date"),
            record.get("contract_value_try"),
            record.get("item_name"),
        )
        if key in seen:
            continue
        seen.add(key)
        output.append(record)
    return output


def _contract_key(record: dict) -> tuple:
    return (
        record.get("tender_id"),
        record.get("winning_company"),
        record.get("contract_date"),
        record.get("contract_value_try"),
    )


def rank_companies_by_unique_tenders(records: list[dict]) -> list[dict]:
    grouped: dict[str, list[dict]] = defaultdict(list)
    for record in records:
        company = normalize_company_name(record.get("winning_company"))
        if company:
            grouped[company].append(record)

    tender_fields = [
        "tender_name",
        "buyer_institution",
        "procurement_type",
        "procedure_type",
        "location",
        "tender_date",
        "result_status",
        "winning_company",
        "contract_value_try",
        "estimated_cost_try",
        "contract_date",
        "highest_bid_try",
        "lowest_bid_try",
        "termination_status",
        "transfer_status",
        "item_details_available",
    ]

    rows: list[dict] = []
    max_unique_tenders = 0
    for company, company_records in grouped.items():
        tenders: dict[str, list[dict]] = defaultdict(list)
        for record in company_records:
            tenders[record.get("tender_id") or ""].append(record)

        completeness_values: list[float] = []
        for tender_records in tenders.values():
            present = 0
            for field in tender_fields:
                if any(record.get(field) not in (None, "", False) for record in tender_records):
                    present += 1
            completeness_values.append(present / len(tender_fields))

        unique_tenders = len(tenders)
        max_unique_tenders = max(max_unique_tenders, unique_tenders)
        completeness_score = sum(completeness_values) / len(completeness_values) if completeness_values else 0
        rows.append(
            {
                "company": company,
                "unique_tenders": unique_tenders,
                "unique_contracts": len({_contract_key(record) for record in company_records}),
                "item_rows": len(company_records),
                "completeness_score": round(completeness_score, 4),
                "final_score": 0,
                "selected": False,
            }
        )

    for row in rows:
        tender_component = row["unique_tenders"] / max_unique_tenders if max_unique_tenders else 0
        row["final_score"] = round((0.7 * tender_component) + (0.3 * row["completeness_score"]), 6)

    rows.sort(
        key=lambda row: (
            row["final_score"],
            row["unique_tenders"],
            row["completeness_score"],
            row["unique_contracts"],
            row["item_rows"],
        ),
        reverse=True,
    )
    if rows:
        rows[0]["selected"] = True
    return rows


@dataclass
class DiscoveryResult:
    listing_rows: list[dict]
    records: list[dict]
    company_ranking_unique_tenders: list[dict]
    blocked_pages: list[dict]
    checked_count: int


def discover_companies(
    max_completed_tenders: int = 150,
    page_size: int = 50,
    delay_seconds: float = 0.4,
) -> DiscoveryResult:
    session = requests.Session()
    listing_rows: list[dict] = []
    records: list[dict] = []
    blocked_pages: list[dict] = []

    for skip in range(0, max_completed_tenders, page_size):
        take = min(page_size, max_completed_tenders - skip)
        search_payload = search_completed_tenders(session, skip=skip, take=take)
        rows = search_payload.get("list") or []
        listing_rows.extend(rows)
        if not rows:
            break
        time.sleep(delay_seconds)

    for row in listing_rows[:max_completed_tenders]:
        try:
            detail = fetch_tender_detail(session, row)
            records.extend(extract_contract_records(row, detail))
        except requests.RequestException as exc:
            blocked_pages.append({"tender_id": row.get("ikn"), "source_url": source_url_for_ikn(row.get("ikn")), "reason": str(exc)})
        except (KeyError, ValueError, TypeError) as exc:
            blocked_pages.append({"tender_id": row.get("ikn"), "source_url": source_url_for_ikn(row.get("ikn")), "reason": f"parse_error: {exc}"})
        time.sleep(delay_seconds)

    records = dedupe_records(records)
    unique_ranking = rank_companies_by_unique_tenders(records)
    return DiscoveryResult(
        listing_rows=listing_rows,
        records=records,
        company_ranking_unique_tenders=unique_ranking,
        blocked_pages=blocked_pages,
        checked_count=len(listing_rows[:max_completed_tenders]),
    )


def write_discovery_outputs(result: DiscoveryResult) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    discovery_payload = {
        "source": "EKAP v2 İhale Arama",
        "source_url": SEARCH_PAGE_URL,
        "status_filter": COMPLETED_STATUS_TEXT,
        "completed_tenders_checked": result.checked_count,
        "listing_rows": result.listing_rows,
        "records": result.records,
        "blocked_pages": result.blocked_pages,
    }
    DISCOVERY_OUTPUT.write_text(json.dumps(discovery_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    RANKING_UNIQUE_TENDERS_OUTPUT.write_text(
        json.dumps(result.company_ranking_unique_tenders, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-completed-tenders", type=int, default=150)
    parser.add_argument("--page-size", type=int, default=50)
    parser.add_argument("--delay-seconds", type=float, default=0.4)
    parser.add_argument("--log-level", default="INFO")
    args = parser.parse_args()
    logging.basicConfig(level=args.log_level.upper(), format="%(levelname)s %(message)s")

    result = discover_companies(args.max_completed_tenders, args.page_size, args.delay_seconds)
    write_discovery_outputs(result)
    logging.info("Checked %s completed EKAP tenders", result.checked_count)
    logging.info("Extracted %s contract records", len(result.records))
    logging.info("Ranked %s companies", len(result.company_ranking_unique_tenders))
    if result.company_ranking_unique_tenders:
        logging.info("Top company: %s", result.company_ranking_unique_tenders[0]["company"])


if __name__ == "__main__":
    main()
